# -*- coding: utf-8 -*-
"""DAY 1 ASSIGNMENT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WbsZPkzpTdFo4MvX37LMyvqrpRxP1xZp
"""

x=int(input())
y= int(input())
print(x**y)